language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: php -f demo/transavia.php BCN CRA $(date -d 'next saturday' +%Y-%m-%d) $(date -d 'next saturday next month' +%Y-%m-%d)
